version: '3.9'

services:
  back-end:
    container_name: contact_management_back
    build:
      context: ./back-end/
    ports:
      - $PORT:$PORT
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
    command: sh -c "yarn prisma migrate dev && yarn start:dev"
    volumes:
      - ./back-end/:/app 
    
  database:
    container_name: db_contact_management
    image: postgres:15
    ports:
      - 5432:5432
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 5s

  front-end:
    container_name: contact_management_front
    build:
      context: ./front-end/
    ports:
      - "3000:3000" 
    depends_on:
      - back-end
    command: sh -c "yarn dev"
    volumes:
      - ./front-end/:/app